#include <iostream>
#include <string>


using namespace std;

int main(){
    string dictionary;

    cout << "Search your word: ";
    cin >> dictionary;

    getline(cin, dictionary);

    if (dictionary == "ABACUS") {
        cout << "AROUND 4000 YEARS AGO, THE CHINESE INVENTED THE ABACUS. IT IS BELIEVED TO BE THE FIRST COMPUTER. IT WAS MADE FROM WOODEN RACK THAT HAS METAL RODS WITH BEADS ATTACH TO THEM.";
    } else if (dictionary == "NAPIER'S BONE") {
        cout << "INVENTED BY JOHN NAPIER, THIS DEVICE USES 9 DIFFERENT IVORY STRIPS MARKED WITH NUMBERS TO MULTIPLY AND DIVIDE FOR CALCULATIONS.";
    } else if (dictionary == "PASCALINE") {
        cout << "INVENTED BY FRENCH MATHEMATICIAN-PHILOSOPHER BLAISE PASCAL. THE FIRST MECHANICAL AND AUTOMATIC CALCULATOR. IT COULD PERFORM ADDITION AND SUBTRACTION IN QUICK TIME.";
    } else if (dictionary == "STEPPED RECKONER") {
        cout << "INVENTED TO DEVELOP PASCAL'S INVENTION BY WILLHELM LEIBNIZ. IT IS ALSO KNOWN AS LEIBNIZ WHEEL. IT IS A DIGITAL MECHANICAL CALCULATOR AND WAS MADE OF FLUTED DRUMS INSTEAD OF GEARS.";
    } else if (dictionary == "ANALYTICAL ENGINE") {
        cout << "INVENTED BY CHARLES BABBAGE, A MECHANICAL COMPUTER THAT USED PUNCH CARDS AS INPUT. IT WAS CAPABLE OF PERFORMING OR SOLVING ANY MATHEMATICAL PROBLEM AND STORING INFORMATION AS A PERMANENT MEMORY.";
    } else if (dictionary == "TABULATING MACHINE") {
        cout << "INVENTED BY HERMAN HOLLERITH, A MECHANICAL TABULATOR THAT WAS BASED ON PUNCH CARDS. IT WAS CAPABLE OF TABULATING STATISTICS AND RECORD OR SORT DATA OR INFORMATION.";
    } else if (dictionary == "DIFFERENTIAL ANALYZER") {
        cout << "WAS THE FIRST ELECTRONIC INTRODUCED IN THE YEAR 1930 IN THE U.S, AN ANALOG DEVICE THAT WAS INVENTED BY VANNERVAR BUSH. THIS MACHINE CONSISTS OF VACUUM TUBES TO SWITCH ELECTRICAL SIGNALS TO PERFORM CALCULATIONS.";
    } else if (dictionary == "MARK 1") {
        cout << "INVENTED BY HOWARD AIKEN TO PERFORM LARGE CALCULATIONS OR CALCULATIONS INVOLVING LARGE NUMBERS. WAS BUILT AS A PARTNERSHIP BETWEEN IBM AND HARVARD. FIRST PROGRAMMABLE DIGITAL COMPUTER.";
    } else if (dictionary == "FIRST GENERATION COMPUTERS") {
        cout << "IN THE PERIOD OF THE YEAR 1940-1956, WAS REFERRED TO AS THE PERIOD OF FIRST GENERATION OF COMPUTERS. THESE MACHINES ARE SLOW, HUGE AND EXPENSIVE. VACUUM TUBES WERE USED AS THE BASIC COMPONENTS OF CPU AND MEMORY. IT IS DEPENDENT ON BATCH OPERATING SYSTEMS AND PUNCH CARDS.";
    } else if (dictionary == "SECOND GENERATION COMPUTERS") {
        cout << "IT WAS THE TIME TRANSISTORS WERE USED IN COMPUTERS. TRANSISTOR COMPUTERS ARE FASTER THAN FIRST GENERATION COMPUTERS. FOR PRIMARY MEMORY, MAGNETIC CORES WERE USED, AND FOR SECONDARY MEMORY MAGNETIC DISC AND TAPES FOR STORAGE PURPOSES.";
    } else if (dictionary == "THIRD GENERATION COMPUTERS") {
        cout << "INTEGRATED CIRCUITS ARE USED, ARE MORE RELIABLE, EFFICIENT AND SMALLER IN SIZE. IT USED REMOTE PROCESSING, TIME-SHARING, AND MULTIPROGRAMMING AS OPERATING SYSTEM.";
    } else if (dictionary == "FOURTH GENERATION COMPUTERS") {
        cout << "IT USED VLSI(VERY LARGE SCALE INTEGRATED) CIRCUITS. VLSI IS A CHIP CONTAINING BILLIONS OF TRANSISTORS AND OTHER CIRCUIT ELEMENTS AND BECAUSE OF THESE CHIPS, THE COMPUTERS OF THIS GENERATION ARE MORE COMPACT, POWERFUL, FAST, AND AFFORDABLE.";
    } else if (dictionary == "FIFTH GENERATION COMPUTERS") {
        cout << "USES ULSI(ULTRA LARGE SCALE INTEGRATED) CIRCUITS. MICROPROCESSORS CHIPS WITH TEN MILLION ELECTRONIC COMPONENTS ARE USED IN THESE COMPUTERS. PARALLEL PROCESSING HARDWARE AND AI SOFTWARE ARE ALSO USED IN FIFTH GENERATION. THE PROGRAMMING LANGUAGES LIKE C++, JAVA, .NET, ETC ARE USED.";
    } else {
        cout << "Word not found!";
    }

    return 0;
}